FROM php:7.2-rc-fpm-alpine

RUN apk update
RUN apk add --update \
    php7-fpm \
    php7-apcu \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-gd \
    php7-iconv \
    php7-imagick \
    php7-json \
    php7-intl \
    php7-mcrypt \
    php7-opcache \
    php7-openssl \
    php7-pdo \
    php7-pdo_mysql \
    php7-mysqli \
    php7-xml \
    php7-zlib \
    php7-zip \
    shadow

# Change default Alpine www-data user ID to 1000 to match most common Linux user
RUN usermod -u 1000 www-data
